### ISSUE TITLE
дз1

### ISSUE THREAD

**Issue by roman-semak** [TymohaGoIT/TymohaGoIT.github.io#1]
margin-left: auto;
  margin-right: auto; 

  margin-right: 15px;
  margin-left: 15px;
краще писати в скороченій формі

<hr/> семантично застарілий тег

.content{
  margin:auto;
}
.content{
повтор

```
<div class="content-info">
  <div class="contact">
    <p>Мой контактный телефон<br>+380 (93) 794-17-65</p>
  </div>
```

стиль можна застосувати безпосередньо до тегу <p>  і уникнути при цьому зайвого div

стандартні назви папок css img/i js font
стандартні назви файлів index.html style.css main.js

**Comment by Tymohat** [comment]
поменял на сокращенную форму, убрал тег контакт, изменил структуру папок
